/* ==========================================================================
   Awesome God Ministries — Inbuilt Bible (sample library)
   New Testament: Philippians, Colossians (full books)
   King James Version (public domain)
   ========================================================================== */
window.BIBLE = window.BIBLE || {};

window.BIBLE.php = {
  1: [
    "Paul and Timotheus, the servants of Jesus Christ, to all the saints in Christ Jesus which are at Philippi, with the bishops and deacons:",
    "Grace be unto you, and peace, from God our Father, and from the Lord Jesus Christ.",
    "I thank my God upon every remembrance of you,",
    "Always in every prayer of mine for you all making request with joy,",
    "For your fellowship in the gospel from the first day until now;",
    "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:",
    "Even as it is meet for me to think this of you all, because I have you in my heart; inasmuch as both in my bonds, and in the defence and confirmation of the gospel, ye all are partakers of my grace.",
    "For God is my record, how greatly I long after you all in the bowels of Jesus Christ.",
    "And this I pray, that your love may abound yet more and more in knowledge and in all judgment;",
    "That ye may approve things that are excellent; that ye may be sincere and without offence till the day of Christ;",
    "Being filled with the fruits of righteousness, which are by Jesus Christ, unto the glory and praise of God.",
    "But I would ye should understand, brethren, that the things which happened unto me have fallen out rather unto the furtherance of the gospel;",
    "So that my bonds in Christ are manifest in all the palace, and in all other places;",
    "And many of the brethren in the Lord, waxing confident by my bonds, are much more bold to speak the word without fear.",
    "Some indeed preach Christ even of envy and strife; and some also of good will:",
    "The one preach Christ of contention, not sincerely, supposing to add affliction to my bonds:",
    "But the other of love, knowing that I am set for the defence of the gospel.",
    "What then? notwithstanding, every way, whether in pretence, or in truth, Christ is preached; and I therein do rejoice, yea, and will rejoice.",
    "For I know that this shall turn to my salvation through your prayer, and the supply of the Spirit of Jesus Christ,",
    "According to my earnest expectation and my hope, that in nothing I shall be ashamed, but that with all boldness, as always, so now also Christ shall be magnified in my body, whether it be by life, or by death.",
    "For to me to live is Christ, and to die is gain.",
    "But if I live in the flesh, this is the fruit of my labour: yet what I shall choose I wot not.",
    "For I am in a strait betwixt two, having a desire to depart, and to be with Christ; which is far better:",
    "Nevertheless to abide in the flesh is more needful for you.",
    "And having this confidence, I know that I shall abide and continue with you all for your furtherance and joy of faith;",
    "That your rejoicing may be more abundant in Jesus Christ for me by my coming to you again.",
    "Only let your conversation be as it becometh the gospel of Christ: that whether I come and see you, or else be absent, I may hear of your affairs, that ye stand fast in one spirit, with one mind striving together for the faith of the gospel;",
    "And in nothing terrified by your adversaries: which is to them an evident token of perdition, but to you of salvation, and that of God.",
    "For unto you it is given in the behalf of Christ, not only to believe on him, but also to suffer for his sake;",
    "Having the same conflict which ye saw in me, and now hear to be in me."
  ],
  2: [
    "If there be therefore any consolation in Christ, if any comfort of love, if any fellowship of the Spirit, if any bowels and mercies,",
    "Fulfil ye my joy, that ye be likeminded, having the same love, being of one accord, of one mind.",
    "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
    "Look not every man on his own things, but every man also on the things of others.",
    "Let this mind be in you, which was also in Christ Jesus:",
    "Who, being in the form of God, thought it not robbery to be equal with God:",
    "But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men:",
    "And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross.",
    "Wherefore God also hath highly exalted him, and given him a name which is above every name:",
    "That at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things under the earth;",
    "And that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.",
    "Wherefore, my beloved, as ye have always obeyed, not as in my presence only, but now much more in my absence, work out your own salvation with fear and trembling.",
    "For it is God which worketh in you both to will and to do of his good pleasure.",
    "Do all things without murmurings and disputings:",
    "That ye may be blameless and harmless, the sons of God, without rebuke, in the midst of a crooked and perverse nation, among whom ye shine as lights in the world;",
    "Holding forth the word of life; that I may rejoice in the day of Christ, that I have not run in vain, neither laboured in vain.",
    "Yea, and if I be offered upon the sacrifice and service of your faith, I joy, and rejoice with you all.",
    "For the same cause also do ye joy, and rejoice with me.",
    "But I trust in the Lord Jesus to send Timotheus shortly unto you, that I also may be of good comfort, when I know your state.",
    "For I have no man likeminded, who will naturally care for your state.",
    "For all seek their own, not the things which are Jesus Christ's.",
    "But ye know the proof of him, that, as a son with the father, he hath served with me in the gospel.",
    "Him therefore I hope to send presently, so soon as I shall see how it will go with me.",
    "But I trust in the Lord that I also myself shall come shortly.",
    "Yet I supposed it necessary to send to you Epaphroditus, my brother, and companion in labour, and fellowsoldier, but your messenger, and he that ministered to my wants.",
    "For he longed after you all, and was full of heaviness, because that ye had heard that he had been sick.",
    "For indeed he was sick nigh unto death: but God had mercy on him; and not on him only, but on me also, lest I should have sorrow upon sorrow.",
    "I sent him therefore the more carefully, that, when ye see him again, ye may rejoice, and that I may be the less sorrowful.",
    "Receive him therefore in the Lord with all gladness; and hold such in reputation:",
    "Because for the work of Christ he was nigh unto death, not regarding his life, to supply your lack of service toward me."
  ],
  3: [
    "Finally, my brethren, rejoice in the Lord. To write the same things to you, to me indeed is not grievous, but for you it is safe.",
    "Beware of dogs, beware of evil workers, beware of the concision.",
    "For we are the circumcision, which worship God in the spirit, and rejoice in Christ Jesus, and have no confidence in the flesh.",
    "Though I might also have confidence in the flesh. If any other man thinketh that he hath whereof he might trust in the flesh, I more:",
    "Circumcised the eighth day, of the stock of Israel, of the tribe of Benjamin, an Hebrew of the Hebrews; as touching the law, a Pharisee;",
    "Concerning zeal, persecuting the church; touching the righteousness which is in the law, blameless.",
    "But what things were gain to me, those I counted loss for Christ.",
    "Yea doubtless, and I count all things but loss for the excellency of the knowledge of Christ Jesus my Lord: for whom I have suffered the loss of all things, and do count them but dung, that I may win Christ,",
    "And be found in him, not having mine own righteousness, which is of the law, but that which is through the faith of Christ, the righteousness which is of God by faith:",
    "That I may know him, and the power of his resurrection, and the fellowship of his sufferings, being made conformable unto his death;",
    "If by any means I might attain unto the resurrection of the dead.",
    "Not as though I had already attained, either were already perfect: but I follow after, if that I may apprehend that for which also I am apprehended of Christ Jesus.",
    "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before,",
    "I press toward the mark for the prize of the high calling of God in Christ Jesus.",
    "Let us therefore, as many as be perfect, be thus minded: and if in any thing ye be otherwise minded, God shall reveal even this unto you.",
    "Nevertheless, whereto we have already attained, let us walk by the same rule, let us mind the same thing.",
    "Brethren, be followers together of me, and mark them which walk so as ye have us for an ensample.",
    "(For many walk, of whom I have told you often, and now tell you even weeping, that they are the enemies of the cross of Christ:",
    "Whose end is destruction, whose God is their belly, and whose glory is in their shame, who mind earthly things.)",
    "For our conversation is in heaven; from whence also we look for the Saviour, the Lord Jesus Christ:",
    "Who shall change our vile body, that it may be fashioned like unto his glorious body, according to the working whereby he is able even to subdue all things unto himself."
  ],
  4: [
    "Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord, my dearly beloved.",
    "I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord.",
    "And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and with other my fellowlabourers, whose names are in the book of life.",
    "Rejoice in the Lord alway: and again I say, Rejoice.",
    "Let your moderation be known unto all men. The Lord is at hand.",
    "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
    "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.",
    "Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you.",
    "But I rejoiced in the Lord greatly, that now at the last your care of me hath flourished again; wherein ye were also careful, but ye lacked opportunity.",
    "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content.",
    "I know both how to be abased, and I know how to abound: every where and in all things I am instructed both to be full and to be hungry, both to abound and to suffer need.",
    "I can do all things through Christ which strengtheneth me.",
    "Notwithstanding ye have well done, that ye did communicate with my affliction.",
    "Now ye Philippians know also, that in the beginning of the gospel, when I departed from Macedonia, no church communicated with me as concerning giving and receiving, but ye only.",
    "For even in Thessalonica ye sent once and again unto my necessity.",
    "Not because I desire a gift: but I desire fruit that may abound to your account.",
    "But I have all, and abound: I am full, having received of Epaphroditus the things which were sent from you, an odour of a sweet smell, a sacrifice acceptable, wellpleasing to God.",
    "But my God shall supply all your need according to his riches in glory by Christ Jesus.",
    "Now unto God and our Father be glory for ever and ever. Amen.",
    "Salute every saint in Christ Jesus. The brethren which are with me greet you.",
    "All the saints salute you, chiefly they that are of Caesar's household.",
    "The grace of our Lord Jesus Christ be with you all. Amen."
  ]
};

window.BIBLE.col = {
  1: [
    "Paul, an apostle of Jesus Christ by the will of God, and Timotheus our brother,",
    "To the saints and faithful brethren in Christ which are at Colosse: Grace be unto you, and peace, from God our Father and the Lord Jesus Christ.",
    "We give thanks to God and the Father of our Lord Jesus Christ, praying always for you,",
    "Since we heard of your faith in Christ Jesus, and of the love which ye have to all the saints,",
    "For the hope which is laid up for you in heaven, whereof ye heard before in the word of the truth of the gospel;",
    "Which is come unto you, as it is in all the world; and bringeth forth fruit, as it doth also in you, since the day ye heard of it, and knew the grace of God in truth:",
    "As ye also learned of Epaphras our dear fellowservant, who is for you a faithful minister of Christ;",
    "Who also declared unto us your love in the Spirit.",
    "For this cause we also, since the day we heard it, do not cease to pray for you, and to desire that ye might be filled with the knowledge of his will in all wisdom and spiritual understanding;",
    "That ye might walk worthy of the Lord unto all pleasing, being fruitful in every good work, and increasing in the knowledge of God;",
    "Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness;",
    "Giving thanks unto the Father, which hath made us meet to be partakers of the inheritance of the saints in light:",
    "Who hath delivered us from the power of darkness, and hath translated us into the kingdom of his dear Son:",
    "In whom we have redemption through his blood, even the forgiveness of sins:",
    "Who is the image of the invisible God, the firstborn of every creature:",
    "For by him were all things created, that are in heaven, and that are in earth, visible and invisible, whether they be thrones, or dominions, or principalities, or powers: all things were created by him, and for him:",
    "And he is before all things, and by him all things consist.",
    "And he is the head of the body, the church: who is the beginning, the firstborn from the dead; that in all things he might have the preeminence.",
    "For it pleased the Father that in him should all fulness dwell;",
    "And, having made peace through the blood of his cross, by him to reconcile all things unto himself; by him, I say, whether they be things in earth, or things in heaven.",
    "And you, that were sometime alienated and enemies in your mind by wicked works, yet now hath he reconciled",
    "In the body of his flesh through death, to present you holy and unblameable and unreproveable in his sight:",
    "If ye continue in the faith grounded and settled, and be not moved away from the hope of the gospel, which ye have heard, and which was preached to every creature which is under heaven; whereof I Paul am made a minister;",
    "Who now rejoice in my sufferings for you, and fill up that which is behind of the afflictions of Christ in my flesh for his body's sake, which is the church:",
    "Whereof I am made a minister, according to the dispensation of God which is given to me for you, to fulfil the word of God;",
    "Even the mystery which hath been hid from ages and from generations, but now is made manifest to his saints:",
    "To whom God would make known what is the riches of the glory of this mystery among the Gentiles; which is Christ in you, the hope of glory:",
    "Whom we preach, warning every man, and teaching every man in all wisdom; that we may present every man perfect in Christ Jesus:",
    "Whereunto I also labour, striving according to his working, which worketh in me mightily."
  ],
  2: [
    "For I would that ye knew what great conflict I have for you, and for them at Laodicea, and for as many as have not seen my face in the flesh;",
    "That their hearts might be comforted, being knit together in love, and unto all riches of the full assurance of understanding, to the acknowledgement of the mystery of God, and of the Father, and of Christ;",
    "In whom are hid all the treasures of wisdom and knowledge.",
    "And this I say, lest any man should beguile you with enticing words.",
    "For though I be absent in the flesh, yet am I with you in the spirit, joying and beholding your order, and the stedfastness of your faith in Christ.",
    "As ye have therefore received Christ Jesus the Lord, so walk ye in him:",
    "Rooted and built up in him, and stablished in the faith, as ye have been taught, abounding therein with thanksgiving.",
    "Beware lest any man spoil you through philosophy and vain deceit, after the tradition of men, after the rudiments of the world, and not after Christ.",
    "For in him dwelleth all the fulness of the Godhead bodily.",
    "And ye are complete in him, which is the head of all principality and power:",
    "In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ:",
    "Buried with him in baptism, wherein also ye are risen with him through the faith of the operation of God, who hath raised him from the dead.",
    "And you, being dead in your sins and the uncircumcision of your flesh, hath he quickened together with him, having forgiven you all trespasses;",
    "Blotting out the handwriting of ordinances that was against us, which was contrary to us, and took it out of the way, nailing it to his cross;",
    "And having spoiled principalities and powers, he made a shew of them openly, triumphing over them in it.",
    "Let no man therefore judge you in meat, or in drink, or in respect of an holyday, or of the new moon, or of the sabbath days:",
    "Which are a shadow of things to come; but the body is of Christ.",
    "Let no man beguile you of your reward in a voluntary humility and worshipping of angels, intruding into those things which he hath not seen, vainly puffed up by his fleshly mind,",
    "And not holding the Head, from which all the body by joints and bands having nourishment ministered, and knit together, increaseth with the increase of God.",
    "Wherefore if ye be dead with Christ from the rudiments of the world, why, as though living in the world, are ye subject to ordinances,",
    "(Touch not; taste not; handle not;",
    "Which all are to perish with the using;) after the commandments and doctrines of men?",
    "Which things have indeed a shew of wisdom in will worship, and humility, and neglecting of the body; not in any honour to the satisfying of the flesh."
  ],
  3: [
    "If ye then be risen with Christ, seek those things which are above, where Christ sitteth on the right hand of God.",
    "Set your affection on things above, not on things on the earth.",
    "For ye are dead, and your life is hid with Christ in God.",
    "When Christ, who is our life, shall appear, then shall ye also appear with him in glory.",
    "Mortify therefore your members which are upon the earth; fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness, which is idolatry:",
    "For which things' sake the wrath of God cometh on the children of disobedience:",
    "In the which ye also walked some time, when ye lived in them.",
    "But now ye also put off all these; anger, wrath, malice, blasphemy, filthy communication out of your mouth.",
    "Lie not one to another, seeing that ye have put off the old man with his deeds;",
    "And have put on the new man, which is renewed in knowledge after the image of him that created him:",
    "Where there is neither Greek nor Jew, circumcision nor uncircumcision, Barbarian, Scythian, bond nor free: but Christ is all, and in all.",
    "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering;",
    "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.",
    "And above all these things put on charity, which is the bond of perfectness.",
    "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.",
    "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.",
    "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.",
    "Wives, submit yourselves unto your own husbands, as it is fit in the Lord.",
    "Husbands, love your wives, and be not bitter against them.",
    "Children, obey your parents in all things: for this is well pleasing unto the Lord.",
    "Fathers, provoke not your children to anger, lest they be discouraged.",
    "Servants, obey in all things your masters according to the flesh; not with eyeservice, as menpleasers; but in singleness of heart, fearing God:",
    "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;",
    "Knowing that of the Lord ye shall receive the reward of the inheritance: for ye serve the Lord Christ.",
    "But he that doeth wrong shall receive for the wrong which he hath done: and there is no respect of persons."
  ],
  4: [
    "Masters, give unto your servants that which is just and equal; knowing that ye also have a Master in heaven.",
    "Continue in prayer, and watch in the same with thanksgiving;",
    "Withal praying also for us, that God would open unto us a door of utterance, to speak the mystery of Christ, for which I am also in bonds:",
    "That I may make it manifest, as I ought to speak.",
    "Walk in wisdom toward them that are without, redeeming the time.",
    "Let your speech be alway with grace, seasoned with salt, that ye may know how ye ought to answer every man.",
    "All my state shall Tychicus declare unto you, who is a beloved brother, and a faithful minister and fellowservant in the Lord:",
    "Whom I have sent unto you for the same purpose, that he might know your estate, and comfort your hearts;",
    "With Onesimus, a faithful and beloved brother, who is one of you. They shall make known unto you all things which are done here.",
    "Aristarchus my fellowprisoner saluteth you, and Marcus, sister's son to Barnabas, (touching whom ye received commandments: if he come unto you, receive him;)",
    "And Jesus, which is called Justus, who are of the circumcision. These only are my fellowworkers unto the kingdom of God, which have been a comfort unto me.",
    "Epaphras, who is one of you, a servant of Christ, saluteth you, always labouring fervently for you in prayers, that ye may stand perfect and complete in all the will of God.",
    "For I bear him record, that he hath a great zeal for you, and them that are in Laodicea, and them in Hierapolis.",
    "Luke, the beloved physician, and Demas, greet you.",
    "Salute the brethren which are in Laodicea, and Nymphas, and the church which is in his house.",
    "And when this epistle is read among you, cause that it be read also in the church of the Laodiceans; and that ye likewise read the epistle from Laodicea.",
    "And say to Archippus, Take heed to the ministry which thou hast received in the Lord, that thou fulfil it.",
    "The salutation by the hand of me Paul. Remember my bonds. Grace be with you. Amen."
  ]
};
