/* ==========================================================================
   Awesome God Ministries — Inbuilt Bible (sample library)
   New Testament: 1 John, Philemon, Jude (full) + John 3, Romans 8, 1 Cor 13
   King James Version (public domain)
   ========================================================================== */
window.BIBLE = window.BIBLE || {};

window.BIBLE.jhn = {
  3: [
    "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:",
    "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him.",
    "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.",
    "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?",
    "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
    "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit.",
    "Marvel not that I said unto thee, Ye must be born again.",
    "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.",
    "Nicodemus answered and said unto him, How can these things be?",
    "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?",
    "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness.",
    "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?",
    "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven.",
    "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:",
    "That whosoever believeth in him should not perish, but have eternal life.",
    "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
    "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God.",
    "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil.",
    "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved.",
    "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God.",
    "After these things came Jesus and his disciples into the land of Judaea; and there he tarried with them, and baptized.",
    "And John also was baptizing in Aenon near to Salim, because there was much water there: and they came, and were baptized.",
    "For John was not yet cast into prison.",
    "Then there arose a question between some of John's disciples and the Jews about purifying.",
    "And they came unto John, and said unto him, Rabbi, he that was with thee beyond Jordan, to whom thou barest witness, behold, the same baptizeth, and all men come to him.",
    "John answered and said, A man can receive nothing, except it be given him from heaven.",
    "Ye yourselves bear me witness, that I said, I am not the Christ, but that I am sent before him.",
    "He that hath the bride is the bridegroom: but the friend of the bridegroom, which standeth and heareth him, rejoiceth greatly because of the bridegroom's voice: this my joy therefore is fulfilled.",
    "He must increase, but I must decrease.",
    "He that cometh from above is above all: he that is of the earth is earthly, and speaketh of the earth: he that cometh from heaven is above all.",
    "And what he hath seen and heard, that he testifieth; and no man receiveth his testimony.",
    "He that hath received his testimony hath set to his seal that God is true.",
    "For he whom God hath sent speaketh the words of God: for God giveth not the Spirit by measure unto him.",
    "The Father loveth the Son, and hath given all things into his hand.",
    "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him."
  ]
};

window.BIBLE.rom = {
  8: [
    "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
    "For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.",
    "For what the law could not do, in that it was weak through the flesh, God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh:",
    "That the righteousness of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.",
    "For they that are after the flesh do mind the things of the flesh; but they that are after the Spirit the things of the Spirit.",
    "For to be carnally minded is death; but to be spiritually minded is life and peace.",
    "Because the carnal mind is enmity against God: for it is not subject to the law of God, neither indeed can be.",
    "So then they that are in the flesh cannot please God.",
    "But ye are not in the flesh, but in the Spirit, if so be that the Spirit of God dwell in you. Now if any man have not the Spirit of Christ, he is none of his.",
    "And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness.",
    "But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you.",
    "Therefore, brethren, we are debtors, not to the flesh, to live after the flesh.",
    "For if ye live after the flesh, ye shall die: but if ye through the Spirit do mortify the deeds of the body, ye shall live.",
    "For as many as are led by the Spirit of God, they are the sons of God.",
    "For ye have not received the spirit of bondage again to fear; but ye have received the Spirit of adoption, whereby we cry, Abba, Father.",
    "The Spirit itself beareth witness with our spirit, that we are the children of God:",
    "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.",
    "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.",
    "For the earnest expectation of the creature waiteth for the manifestation of the sons of God.",
    "For the creature was made subject to vanity, not willingly, but by reason of him who hath subjected the same in hope,",
    "Because the creature itself also shall be delivered from the bondage of corruption into the glorious liberty of the children of God.",
    "For we know that the whole creation groaneth and travaileth in pain together until now.",
    "And not only they, but ourselves also, which have the firstfruits of the Spirit, even we ourselves groan within ourselves, waiting for the adoption, to wit, the redemption of our body.",
    "For we are saved by hope: but hope that is seen is not hope: for what a man seeth, why doth he yet hope for?",
    "But if we hope for that we see not, then do we with patience wait for it.",
    "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.",
    "And he that searcheth the hearts knoweth what is the mind of the Spirit, because he maketh intercession for the saints according to the will of God.",
    "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    "For whom he did foreknow, he also did predestinate to be conformed to the image of his Son, that he might be the firstborn among many brethren.",
    "Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified.",
    "What shall we then say to these things? If God be for us, who can be against us?",
    "He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?",
    "Who shall lay any thing to the charge of God's elect? It is God that justifieth.",
    "Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us.",
    "Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?",
    "As it is written, For thy sake we are killed all the day long; we are accounted as sheep for the slaughter.",
    "Nay, in all these things we are more than conquerors through him that loved us.",
    "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,",
    "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."
  ]
};

window.BIBLE["1co"] = {
  13: [
    "Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal.",
    "And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing.",
    "And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing.",
    "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,",
    "Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;",
    "Rejoiceth not in iniquity, but rejoiceth in the truth;",
    "Beareth all things, believeth all things, hopeth all things, endureth all things.",
    "Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away.",
    "For we know in part, and we prophesy in part.",
    "But when that which is perfect is come, then that which is in part shall be done away.",
    "When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man, I put away childish things.",
    "For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known.",
    "And now abideth faith, hope, charity, these three; but the greatest of these is charity."
  ]
};

window.BIBLE["1jn"] = {
  1: [
    "That which was from the beginning, which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life;",
    "(For the life was manifested, and we have seen it, and bear witness, and shew unto you that eternal life, which was with the Father, and was manifested unto us;)",
    "That which we have seen and heard declare we unto you, that ye also may have fellowship with us: and truly our fellowship is with the Father, and with his Son Jesus Christ.",
    "And these things write we unto you, that your joy may be full.",
    "This then is the message which we have heard of him, and declare unto you, that God is light, and in him is no darkness at all.",
    "If we say that we have fellowship with him, and walk in darkness, we lie, and do not the truth:",
    "But if we walk in the light, as he is in the light, we have fellowship one with another, and the blood of Jesus Christ his Son cleanseth us from all sin.",
    "If we say that we have no sin, we deceive ourselves, and the truth is not in us.",
    "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.",
    "If we say that we have not sinned, we make him a liar, and his word is not in us."
  ],
  2: [
    "My little children, these things write I unto you, that ye sin not. And if any man sin, we have an advocate with the Father, Jesus Christ the righteous:",
    "And he is the propitiation for our sins: and not for ours only, but also for the sins of the whole world.",
    "And hereby we do know that we know him, if we keep his commandments.",
    "He that saith, I know him, and keepeth not his commandments, is a liar, and the truth is not in him.",
    "But whoso keepeth his word, in him verily is the love of God perfected: hereby know we that we are in him.",
    "He that saith he abideth in him ought himself also so to walk, even as he walked.",
    "Brethren, I write no new commandment unto you, but an old commandment which ye had from the beginning. The old commandment is the word which ye have heard from the beginning.",
    "Again, a new commandment I write unto you, which thing is true in him and in you: because the darkness is past, and the true light now shineth.",
    "He that saith he is in the light, and hateth his brother, is in darkness even until now.",
    "He that loveth his brother abideth in the light, and there is none occasion of stumbling in him.",
    "But he that hateth his brother is in darkness, and walketh in darkness, and knoweth not whither he goeth, because that darkness hath blinded his eyes.",
    "I write unto you, little children, because your sins are forgiven you for his name's sake.",
    "I write unto you, fathers, because ye have known him that is from the beginning. I write unto you, young men, because ye have overcome the wicked one. I write unto you, little children, because ye have known the Father.",
    "I have written unto you, fathers, because ye have known him that is from the beginning. I have written unto you, young men, because ye are strong, and the word of God abideth in you, and ye have overcome the wicked one.",
    "Love not the world, neither the things that are in the world. If any man love the world, the love of the Father is not in him.",
    "For all that is in the world, the lust of the flesh, and the lust of the eyes, and the pride of life, is not of the Father, but is of the world.",
    "And the world passeth away, and the lust thereof: but he that doeth the will of God abideth for ever.",
    "Little children, it is the last time: and as ye have heard that antichrist shall come, even now are there many antichrists; whereby we know that it is the last time.",
    "They went out from us, but they were not of us; for if they had been of us, they would no doubt have continued with us: but they went out, that they might be made manifest that they were not all of us.",
    "But ye have an unction from the Holy One, and ye know all things.",
    "I have not written unto you because ye know not the truth, but because ye know it, and that no lie is of the truth.",
    "Who is a liar but he that denieth that Jesus is the Christ? He is antichrist, that denieth the Father and the Son.",
    "Whosoever denieth the Son, the same hath not the Father: (but) he that acknowledgeth the Son hath the Father also.",
    "Let that therefore abide in you, which ye have heard from the beginning. If that which ye have heard from the beginning shall remain in you, ye also shall continue in the Son, and in the Father.",
    "And this is the promise that he hath promised us, even eternal life.",
    "These things have I written unto you concerning them that seduce you.",
    "But the anointing which ye have received of him abideth in you, and ye need not that any man teach you: but as the same anointing teacheth you of all things, and is truth, and is no lie, and even as it hath taught you, ye shall abide in him.",
    "And now, little children, abide in him; that, when he shall appear, we may have confidence, and not be ashamed before him at his coming.",
    "If ye know that he is righteous, ye know that every one that doeth righteousness is born of him."
  ],
  3: [
    "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.",
    "Beloved, now are we the sons of God, and it doth not yet appear what we shall be: but we know that, when he shall appear, we shall be like him; for we shall see him as he is.",
    "And every man that hath this hope in him purifieth himself, even as he is pure.",
    "Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law.",
    "And ye know that he was manifested to take away our sins; and in him is no sin.",
    "Whosoever abideth in him sinneth not: whosoever sinneth hath not seen him, neither known him.",
    "Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous.",
    "He that committeth sin is of the devil; for the devil sinneth from the beginning. For this purpose the Son of God was manifested, that he might destroy the works of the devil.",
    "Whosoever is born of God doth not commit sin; for his seed remaineth in him: and he cannot sin, because he is born of God.",
    "In this the children of God are manifest, and the children of the devil: whosoever doeth not righteousness is not of God, neither he that loveth not his brother.",
    "For this is the message that ye heard from the beginning, that we should love one another.",
    "Not as Cain, who was of that wicked one, and slew his brother. And wherefore slew he him? Because his own works were evil, and his brother's righteous.",
    "Marvel not, my brethren, if the world hate you.",
    "We know that we have passed from death unto life, because we love the brethren. He that loveth not his brother abideth in death.",
    "Whosoever hateth his brother is a murderer: and ye know that no murderer hath eternal life abiding in him.",
    "Hereby perceive we the love of God, because he laid down his life for us: and we ought to lay down our lives for the brethren.",
    "But whoso hath this world's good, and seeth his brother have need, and shutteth up his bowels of compassion from him, how dwelleth the love of God in him?",
    "My little children, let us not love in word, neither in tongue; but in deed and in truth.",
    "And hereby we know that we are of the truth, and shall assure our hearts before him.",
    "For if our heart condemn us, God is greater than our heart, and knoweth all things.",
    "Beloved, if our heart condemn us not, then have we confidence toward God.",
    "And whatsoever we ask, we receive of him, because we keep his commandments, and do those things that are pleasing in his sight.",
    "And this is his commandment, That we should believe on the name of his Son Jesus Christ, and love one another, as he gave us commandment.",
    "And he that keepeth his commandments dwelleth in him, and he in him. And hereby we know that he abideth in us, by the Spirit which he hath given us."
  ],
  4: [
    "Beloved, believe not every spirit, but try the spirits whether they are of God: because many false prophets are gone out into the world.",
    "Hereby know ye the Spirit of God: Every spirit that confesseth that Jesus Christ is come in the flesh is of God:",
    "And every spirit that confesseth not that Jesus Christ is come in the flesh is not of God: and this is that spirit of antichrist, whereof ye have heard that it should come; and even now already is it in the world.",
    "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world.",
    "They are of the world: therefore speak they of the world, and the world heareth them.",
    "We are of God: he that knoweth God heareth us; he that is not of God heareth not us. Hereby know we the spirit of truth, and the spirit of error.",
    "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God.",
    "He that loveth not knoweth not God; for God is love.",
    "In this was manifested the love of God toward us, because that God sent his only begotten Son into the world, that we might live through him.",
    "Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins.",
    "Beloved, if God so loved us, we ought also to love one another.",
    "No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us.",
    "Hereby know we that we dwell in him, and he in us, because he hath given us of his Spirit.",
    "And we have seen and do testify that the Father sent the Son to be the Saviour of the world.",
    "Whosoever shall confess that Jesus is the Son of God, God dwelleth in him, and he in God.",
    "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.",
    "Herein is our love made perfect, that we may have boldness in the day of judgment: because as he is, so are we in this world.",
    "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love.",
    "We love him, because he first loved us.",
    "If a man say, I love God, and hateth his brother, he is a liar: for he that loveth not his brother whom he hath seen, how can he love God whom he hath not seen?",
    "And this commandment have we from him, That he who loveth God love his brother also."
  ],
  5: [
    "Whosoever believeth that Jesus is the Christ is born of God: and every one that loveth him that begat loveth him also that is begotten of him.",
    "By this we know that we love the children of God, when we love God, and keep his commandments.",
    "For this is the love of God, that we keep his commandments: and his commandments are not grievous.",
    "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith.",
    "Who is he that overcometh the world, but he that believeth that Jesus is the Son of God?",
    "This is he that came by water and blood, even Jesus Christ; not by water only, but by water and blood. And it is the Spirit that beareth witness, because the Spirit is truth.",
    "For there are three that bear record in heaven, the Father, the Word, and the Holy Ghost: and these three are one.",
    "And there are three that bear witness in earth, the spirit, and the water, and the blood: and these three agree in one.",
    "If we receive the witness of men, the witness of God is greater: for this is the witness of God which he hath testified of his Son.",
    "He that believeth on the Son of God hath the witness in himself: he that believeth not God hath made him a liar; because he believeth not the record that God gave of his Son.",
    "And this is the record, that God hath given to us eternal life, and this life is in his Son.",
    "He that hath the Son hath life; and he that hath not the Son of God hath not life.",
    "These things have I written unto you that believe on the name of the Son of God; that ye may know that ye have eternal life, and that ye may believe on the name of the Son of God.",
    "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us:",
    "And if we know that he hear us, whatsoever we ask, we know that we have the petitions that we desired of him.",
    "If any man see his brother sin a sin which is not unto death, he shall ask, and he shall give him life for them that sin not unto death. There is a sin unto death: I do not say that he shall pray for it.",
    "All unrighteousness is sin: and there is a sin not unto death.",
    "We know that whosoever is born of God sinneth not; but he that is begotten of God keepeth himself, and that wicked one toucheth him not.",
    "And we know that we are of God, and the whole world lieth in wickedness.",
    "And we know that the Son of God is come, and hath given us an understanding, that we may know him that is true, and we are in him that is true, even in his Son Jesus Christ. This is the true God, and eternal life.",
    "Little children, keep yourselves from idols. Amen."
  ]
};

window.BIBLE.phm = {
  1: [
    "Paul, a prisoner of Jesus Christ, and Timothy our brother, unto Philemon our dearly beloved, and fellowlabourer,",
    "And to our beloved Apphia, and Archippus our fellowsoldier, and to the church in thy house:",
    "Grace to you, and peace, from God our Father and the Lord Jesus Christ.",
    "I thank my God, making mention of thee always in my prayers,",
    "Hearing of thy love and faith, which thou hast toward the Lord Jesus, and toward all saints;",
    "That the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in Christ Jesus.",
    "For we have great joy and consolation in thy love, because the bowels of the saints are refreshed by thee, brother.",
    "Wherefore, though I might be much bold in Christ to enjoin thee that which is convenient,",
    "Yet for love's sake I rather beseech thee, being such an one as Paul the aged, and now also a prisoner of Jesus Christ.",
    "I beseech thee for my son Onesimus, whom I have begotten in my bonds:",
    "Which in time past was to thee unprofitable, but now profitable to thee and to me:",
    "Whom I have sent again: thou therefore receive him, that is, mine own bowels:",
    "Whom I would have retained with me, that in thy stead he might have ministered unto me in the bonds of the gospel:",
    "But without thy mind would I do nothing; that thy benefit should not be as it were of necessity, but willingly.",
    "For perhaps he therefore departed for a season, that thou shouldest receive him for ever;",
    "Not now as a servant, but above a servant, a brother beloved, specially to me, but how much more unto thee, both in the flesh, and in the Lord?",
    "If thou count me therefore a partner, receive him as myself.",
    "If he hath wronged thee, or oweth thee ought, put that on mine account;",
    "I Paul have written it with mine own hand, I will repay it: albeit I do not say to thee how thou owest unto me even thine own self besides.",
    "Yea, brother, let me have joy of thee in the Lord: refresh my bowels in the Lord.",
    "Having confidence in thy obedience I wrote unto thee, knowing that thou wilt also do more than I say.",
    "But withal prepare me also a lodging: for I trust that through your prayers I shall be given unto you.",
    "There salute thee Epaphras, my fellowprisoner in Christ Jesus;",
    "Marcus, Aristarchus, Demas, Lucas, my fellowlabourers.",
    "The grace of our Lord Jesus Christ be with your spirit. Amen."
  ]
};

window.BIBLE.jud = {
  1: [
    "Jude, the servant of Jesus Christ, and brother of James, to them that are sanctified by God the Father, and preserved in Jesus Christ, and called:",
    "Mercy unto you, and peace, and love, be multiplied.",
    "Beloved, when I gave all diligence to write unto you of the common salvation, it was needful for me to write unto you, and exhort you that ye should earnestly contend for the faith which was once delivered unto the saints.",
    "For there are certain men crept in unawares, who were before of old ordained to this condemnation, ungodly men, turning the grace of our God into lasciviousness, and denying the only Lord God, and our Lord Jesus Christ.",
    "I will therefore put you in remembrance, though ye once knew this, how that the Lord, having saved the people out of the land of Egypt, afterward destroyed them that believed not.",
    "And the angels which kept not their first estate, but left their own habitation, he hath reserved in everlasting chains under darkness unto the judgment of the great day.",
    "Even as Sodom and Gomorrha, and the cities about them in like manner, giving themselves over to fornication, and going after strange flesh, are set forth for an example, suffering the vengeance of eternal fire.",
    "Likewise also these filthy dreamers defile the flesh, despise dominion, and speak evil of dignities.",
    "Yet Michael the archangel, when contending with the devil he disputed about the body of Moses, durst not bring against him a railing accusation, but said, The Lord rebuke thee.",
    "But these speak evil of those things which they know not: but what they know naturally, as brute beasts, in those things they corrupt themselves.",
    "Woe unto them! for they have gone in the way of Cain, and ran greedily after the error of Balaam for reward, and perished in the gainsaying of Core.",
    "These are spots in your feasts of charity, when they feast with you, feeding themselves without fear: clouds they are without water, carried about of winds; trees whose fruit withereth, without fruit, twice dead, plucked up by the roots;",
    "Raging waves of the sea, foaming out their own shame; wandering stars, to whom is reserved the blackness of darkness for ever.",
    "And Enoch also, the seventh from Adam, prophesied of these, saying, Behold, the Lord cometh with ten thousands of his saints,",
    "To execute judgment upon all, and to convince all that are ungodly among them of all their ungodly deeds which they have ungodly committed, and of all their hard speeches which ungodly sinners have spoken against him.",
    "These are murmurers, complainers, walking after their own lusts; and their mouth speaketh great swelling words, having men's persons in admiration because of advantage.",
    "But, beloved, remember ye the words which were spoken before of the apostles of our Lord Jesus Christ;",
    "How that they told you there should be mockers in the last time, who should walk after their own ungodly lusts.",
    "These be they who separate themselves, sensual, having not the Spirit.",
    "But ye, beloved, building up yourselves on your most holy faith, praying in the Holy Ghost,",
    "Keep yourselves in the love of God, looking for the mercy of our Lord Jesus Christ unto eternal life.",
    "And of some have compassion, making a difference:",
    "And others save with fear, pulling them out of the fire; hating even the garment spotted by the flesh.",
    "Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy,",
    "To the only wise God our Saviour, be glory and majesty, dominion and power, both now and ever. Amen."
  ]
};
